### ISSUE TITLE
22.04 vers 22.10 : colonne "t0.disabled" non trouvée -> Erreur 500

### ISSUE THREAD

**Issue by BruceFeuillette** [PlanningBiblio/PlanningBiblio#849]
Bonjour,
Je viens de pousser la version 22.10 sur notre version 22.04.
La BDD s'est bien mise à jour, mais j'ai une erreur 500 par la suite.
Mes logs d'erreurs Apache m'indique qu'une colonne t0.disabled n'existe pas en base mais est présente dans le code.
Une idée du fix à appliquer ?

`[Fri Jan 13 07:28:45.847653 2023] [php7:error] [pid 824] [client 172.30.3.86:48132] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.disabled' in 'field list' in /var/www/planningbiblio.22.04.xx/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:134\nStack trace:\n#0 /var/www/planningbiblio.22.04.xx/vendor/doctrine/dbal/src/Driver/PDO/Statement.php(134): PDOStatement->execute()\n#1 /var/www/planningbiblio.22.04.xx/vendor/doctrine/dbal/src/Connection.php(1063): Doctrine\\DBAL\\Driver\\PDO\\Statement->execute()\n#2 /var/www/planningbiblio.22.04.xx/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(916): Doctrine\\DBAL\\Connection->executeQuery()\n#3 /var/www/planningbiblio.22.04.xx/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(225): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->loadAll()\n#4 /var/www/planningbiblio.22.04.xx/src/Cron/Crontab.php(21): Doctrine\\ORM\\EntityRepository->findBy()\n#5 /var/www/planningbiblio.22.04.xx/public/include/cron.php(25): App\\Cron\\Crontab->__construct()\n#6 /var/www/planningbiblio.22.04.xx/public/ in /var/www/planningbiblio.22.04.xx/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php on line 67`

**Comment by tixif** [comment]
Bonjour,

Je n'ai pas eu ce problème lors de la maj... Dans les logs c'est l'ancienne version c'est normal ? Juste au cas où...
"/var/www/planningbiblio.22.04.xx/"

seb

**Comment by BruceFeuillette** [comment]
Oui, j'ai été fainéant. :)
Généralement je crée un dossier avec la nouvelle version et j'utilise un lien. Mais pas ce coup-ci , j'ai fait une mise à jour "en place" :)
Je viens de voir que la mise à jour de la BDD ne se passe pas comme il faut.

ALTER TABLE `responsables` CHANGE IF EXISTS `notification` `notification_level1` INT(1) NOT NULL DEFAULT '0' : Erreur
ALTER TABLE `responsables` ADD COLUMN IF NOT EXISTS `notification_level2` INT(1) NOT NULL DEFAULT '0' AFTER `notification_level1` : Erreur
ALTER TABLE `responsables` ADD COLUMN IF NOT EXISTS `level1` INT(1) NOT NULL DEFAULT '1' AFTER `responsable` : Erreur
ALTER TABLE `responsables` ADD COLUMN IF NOT EXISTS `level2` INT(1) NOT NULL DEFAULT '0' AFTER `level1` : Erreur
ALTER TABLE `cron` ADD COLUMN IF NOT EXISTS `disabled` TINYINT(1) NOT NULL DEFAULT '0' AFTER `last`; : Erreur

Je crois que la dernière ligne "explique" le souci.

PS: comme le serveur est virtualisé j'ai fait un snapshot. :)

**Comment by tixif** [comment]
Oui, et les lignes du dessus indiquent d'autres soucis avec d'autres tables... bien joué pour le snapshot, y'a plus qu'à le remettre ;)

**Comment by BruceFeuillette** [comment]
Bon, c'est compliqué. Même PhpMyAdmin ne me laisse pas créer la colonne.
TINYINT semble fonctionner comme du booléen, il ne prend que 0 ou 1 comme valeur. Or le script veut lui mettre 0 en valeur par défaut. Mais 0 est déjà la valeur par défaut.
J'essaie de voir comment je peux créer la colonne.

**Comment by tixif** [comment]
Tu as vu que tu as aussi d'autres erreurs sur les autres tables ?

**Comment by BruceFeuillette** [comment]
Oui oui :)
Je voulais remettre en service le site pour les collègues, donc je pare au plus rapide. Le reste ne me semble pas utilisé couramment.
Je vais revenir à la version 22.04.xx ça me semble un vrai casse tête pour mettre en place la colonne.
Je me demande pourquoi ne pas avoir utilisé du booléen dans ce cas de figure.

**Comment by tixif** [comment]
Pour info on reste sur la 22.04 nous aussi car les statistiques sur la 22.10 ne fonctionnent pas correctement...

**Comment by BruceFeuillette** [comment]
Bon, j'ai jeté l'éponge.
Je crois que les 5 erreurs sont liées. MariaDB ne me laisse pas créer des colonnes qui équivalent à du booléen.
De ce que j'ai vu INT(1) = TINYINT(1) = BOOLEAN.
Il y a probablement un paramètre à changer dans un coin de la base pour qu'elle accepte les colonnes.

**Comment by BruceFeuillette** [comment]
Peut être qu'un des problèmes vient du fait que MariaDB sur les dépôts Ubuntu (j'ai une version 20.04) est la 8 et quelque.
Il faut donc passer à la version 10.5, qui est disponible sur les dépôts de MariaDB.
La version 10.5 supporte l'instruction IF NOT EXISTS, au contraire de la version 8.
La version installée sur le serveur ne peut pas être migrée, il faut faire un dump.
Bref, cela commence à devenir compliqué et dépasse le temps que je veux/peux consacrer à la tâche.

**Comment by alexarn** [comment]
Bonjour @BruceFeuillette,

La version de mariaDB doit être supérieur à 10.* pour Planno 22.10. https://github.com/PlanningBiblio/PlanningBiblio/tree/22.10.xx

Sinon, essayez de refaire les requêtes SQL sans le "IF NOT EXISTS".

**Comment by BruceFeuillette** [comment]
Malheureusement j'ai essayé sans le IF NOT EXISTS et cela ne fonctionne pas.
Précision : je fais des tests sous MariaDB 8 et planno 22.04.
Je suis passé par PHPMyAdmin, en créant via l'interface graphique. Il est impossible de créer une colonne.
MySQL me retourne sans cesse que la valeur par défaut pour "last" n'est pas bonne.
Je commence à me demander si le problème ne vient pas de là.
J'ai demandé la création de la colonne au début de la table et le message est le même. 
![image](https://user-images.githubusercontent.com/4189397/212300538-ab4b3e50-9d2d-4378-aa52-1707f69f6ccf.png)

**Comment by BruceFeuillette** [comment]
Bon, j'ai pu créer la colonne après avoir modifié la valeur par défaut de "last" en la basculant sur la valeur par défaut de MariaDB, à savoir CURRENT_TIMESTAMP.
Est-ce que ce comportement sera différent avec MariaDB 10.5...
Remarque : si MariaDB 10.5 est requis pour la version 22.10, pourquoi ne pas faire un check sur l'update et bloquer l'installation ?

**Comment by BruceFeuillette** [comment]
Bon, c'est bon, j'ai pris mon courage à 2 mains et j'ai tout installé.
J'ai du réimporter la base PlanningBiblio, recréer les utilisateurs MySQL.
Pas d'erreur lors de la mise à jour. Par contre je viens de voir que la valeur par défaut de la colonne last dans la table cron était restée sur current_timestamp(). 
Je ne sais pas si c'est la mise à jour vers la 22.10 qui l'a fait ou si c'était ma modification...
